version: '3.7'
services:
  mongodb:
    image: mongo:mongo-vertx
    container_name: mongo-vertx
    build:
      context: .
      dockerfile: Dockerfile.mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: local
    ports:
      - 27017:27017
    network_mode: "host"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongodb_data_container:
